spring:
  datasource:
    url: jdbc:postgresql://mainline.proxy.rlwy.net:58833/railway
    username: postgres
    password: mmJNbklWXOLJZmLejoNDwEcoyQKTwPSY
  jpa:
    hibernate:
      # 'create' irá apagar e recriar as tabelas na primeira execução.
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

